apiVersion: v2
version: 0.1.21
appVersion: "0.1.21"
name: pacman
description: Pac-Man Demo App for Kubernetes
home: https://github.com/MichaelHaigh/pacman
icon: https://MichaelHaigh.github.io/pacman/icon.png
sources:
  - https://github.com/MichaelHaigh/pacman
maintainers:
  - name: Dean Lewis
    url: https://veducate.co.uk
  - name: Davis Phillips
    url: https://github.com/dav1x/
  - name: Michael Cade
    url: https://vzilla.co.uk/
  - name: Sylvain Huguet
    url: https://www.huguet.me
  - name: Michael Courcy
    url: https://github.com/michaelcourcy
  - name: Michael Haigh
    url: https://github.com/MichaelHaigh
